### ISSUE TITLE
Error: not readable as KeyValues3 text: Line 50: Invalid value 'subclass:'

### ISSUE THREAD

**Issue by r-bman** [robincodex/easy-keyvalues#11]
In Valve's latest game Deadlock there are some nested objects with the keys `subclass` and `panorama`. This results in the error `Error: not readable as KeyValues3 text: Line 50: Invalid value 'subclass:'` when calling `kv3.toObject();`.

Here are some snippets of data that is failing:
```
{
    AbilityCooldown = 
        {
           ...
            m_subclassScaleFunction = subclass:
                {
                   ...
                }
        }
    }
```

```
m_strAbilityImage = panorama:"file://{images}/hud/abilities/weapon_damage.psd"
```

Is this something that can be fixed please? I've tried to have a go at fixing it myself but I failed 😕

**Comment by robincodex** [comment]
Sorry, I don't have Deadlock, can you upload the file?

**Comment by r-bman** [comment]
Thanks for getting back to me. Please find the file below

[abilities.zip](https://github.com/user-attachments/files/16909061/abilities.zip)

**Comment by robincodex** [comment]
Thank you for the file, the new version is now parsing properly.

> Thanks for getting back to me. Please find the file below
> 
> [abilities.zip](https://github.com/user-attachments/files/16909061/abilities.zip)

Thank you for the file, the new version is now parsing properly.

**Comment by r-bman** [comment]
Thanks a lot, it's much appreciated!
