### ISSUE TITLE
ObjectValue格式化的时候Key应该为字符串，不能用数字

### ISSUE THREAD

**Issue by Yue-Ra** [robincodex/easy-keyvalues#12]
const kv = await KeyValues3.Load('weapons.vdata');
kv.Save('weapons.vdata');

**Comment by robincodex** [comment]
居然不允许纯数字的字符串，看KV3格式说明是类JSON，所以这一部分我也是参考了json。

不过你说的这个问题我觉得并不需要我去修复，这个库只是简单解析和序列化KV3，只保证文本格式上与官方KV3文本格式一致，而能不能正常在游戏内解析还是需要以游戏内为准，就如你说的这个`“1”`，引擎内不支持，那么你直接更改为引擎支持的即可，比如`One`啥的

**Comment by robincodex** [comment]
> 问题在于他引擎用的就是"1"，用什么Key并不是我能决定的，所以我才觉得要兼容一下。

我没懂，你给的这个文件[weapons.txt](https://github.com/user-attachments/files/16958622/weapons.txt)是序列化后的？还是原始的，如果原始是没有代引号的，那我的确要兼容一下

**Comment by robincodex** [comment]
> 问题在于他引擎用的就是"1"，用什么Key并不是我能决定的，所以我才觉得要兼容一下。

我懂了，我修一下

**Comment by robincodex** [comment]
已发布新版本了，之前我记错了，我以为是兼容好的

**Comment by robincodex** [comment]
> 感谢修复，来个赞赏码。

这个就不必了，还得感谢你反馈的问题，我自己也有用这个库，能完善这个库我就很开心了。
