### ISSUE TITLE
需要添加自定义文件格式

### ISSUE THREAD

**Issue by Yue-Ra** [robincodex/easy-keyvalues#13]
现在默认生成出来的文件格式都为generic，也就是
`<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->`

但是比如ModelDoc需要自定义为modeldoc37，完整内容
`<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:modeldoc37:version{9e04b9aa-f073-4e59-8923-ff57489eb2c7} -->`

所以需要一个函数或者变量来支持设置

**Comment by robincodex** [comment]
https://github.com/robincodex/easy-keyvalues/commit/b3d4c746622d275393f9a475b2ef93c4011d5fd4 加了，之前发现了没加这个，一直忘到现在。。。
